print("Hello, World!")
print("Welcome to Ganesh's Python script.")
print("This script is a simple demonstration.")
print("Hello, World!")
print("Welcome to Ganesh's Python script.")
print("This script is a simple demonstration.")
print("Hello, World!")
print("Welcome to Ganesh's Python script.")
print("This script is a simple demonstration.")
print("Hello, World!")
print("Welcome to Ganesh's Python script.")